on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install smlpkg
        run: |
          wget https://github.com/diku-dk/smlpkg/releases/download/v0.1.4/smlpkg-bin-dist-linux.tgz
          tar xzf smlpkg-bin-dist-linux.tgz
          echo "$(pwd)/smlpkg-bin-dist-linux/bin" >> $GITHUB_PATH

      - name: Install Compiler
        run: |
          sudo apt-get install -y polyml libpolyml-dev
          poly -v

      - name: Build
        run: |
          smlpkg --version
          smlpkg sync
          ./build.sh

          echo "## Binary info" >> $GITHUB_STEP_SUMMARY
          ls -l _build/isit2038 >> $GITHUB_STEP_SUMMARY

      - name: Build Container
        run: |
          ./build.container.sh

          echo "## Container image info" >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
          docker image ls isit2038 | grep -v REPOSITORY >> $GITHUB_STEP_SUMMARY
          echo "```" >> $GITHUB_STEP_SUMMARY
